In [2]:
import pandas as pd
import numpy as np
import pickle

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score

import warnings
warnings.filterwarnings("ignore")

In [3]:
X_train = pd.read_csv("../Dataset/X_train.csv")
X_test = pd.read_csv("../Dataset/X_test.csv")

y_train = pd.read_csv("../Dataset/y_train.csv").squeeze()
y_test = pd.read_csv("../Dataset/y_test.csv").squeeze()

In [4]:
print("X_train Shape :", X_train.shape)
print("X_test Shape  :", X_test.shape)
print("y_train Shape :", y_train.shape)
print("y_test Shape  :", y_test.shape)

X_train Shape : (684, 11)
X_test Shape  : (123, 11)
y_train Shape : (684,)
y_test Shape  : (123,)


In [5]:
# DecisionTree

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

train_pred = dt_model.predict(X_train)
test_pred = dt_model.predict(X_test)

print("Training Accuracy :", accuracy_score(y_train, train_pred))
print("Testing Accuracy  :", accuracy_score(y_test, test_pred))

Training Accuracy : 1.0
Testing Accuracy  : 0.6422764227642277


In [6]:
print(confusion_matrix(y_test, test_pred))

[[20 23]
 [21 59]]


In [7]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.49      0.47      0.48        43
           1       0.72      0.74      0.73        80

    accuracy                           0.64       123
   macro avg       0.60      0.60      0.60       123
weighted avg       0.64      0.64      0.64       123



In [8]:
# Random Forest Model

rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

train_pred = rf_model.predict(X_train)
test_pred = rf_model.predict(X_test)

print("Training Accuracy :", accuracy_score(y_train, train_pred))
print("Testing Accuracy  :", accuracy_score(y_test, test_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, test_pred))

print("\nClassification Report")
print(classification_report(y_test, test_pred))

Training Accuracy : 1.0
Testing Accuracy  : 0.7154471544715447

Confusion Matrix
[[19 24]
 [11 69]]

Classification Report
              precision    recall  f1-score   support

           0       0.63      0.44      0.52        43
           1       0.74      0.86      0.80        80

    accuracy                           0.72       123
   macro avg       0.69      0.65      0.66       123
weighted avg       0.70      0.72      0.70       123



In [9]:
# KNN Model

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

train_pred = knn_model.predict(X_train)
test_pred = knn_model.predict(X_test)

print("Training Accuracy :", accuracy_score(y_train, train_pred))
print("Testing Accuracy  :", accuracy_score(y_test, test_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, test_pred))

print("\nClassification Report")
print(classification_report(y_test, test_pred))

Training Accuracy : 0.8654970760233918
Testing Accuracy  : 0.6260162601626016

Confusion Matrix
[[22 21]
 [25 55]]

Classification Report
              precision    recall  f1-score   support

           0       0.47      0.51      0.49        43
           1       0.72      0.69      0.71        80

    accuracy                           0.63       123
   macro avg       0.60      0.60      0.60       123
weighted avg       0.63      0.63      0.63       123



In [10]:
# Gradient Boosting Model

gb_model = GradientBoostingClassifier(random_state=42)

gb_model.fit(X_train, y_train)

train_pred = gb_model.predict(X_train)
test_pred = gb_model.predict(X_test)

print("Training Accuracy :", accuracy_score(y_train, train_pred))
print("Testing Accuracy  :", accuracy_score(y_test, test_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, test_pred))

print("\nClassification Report")
print(classification_report(y_test, test_pred))

Training Accuracy : 0.9093567251461988
Testing Accuracy  : 0.7317073170731707

Confusion Matrix
[[19 24]
 [ 9 71]]

Classification Report
              precision    recall  f1-score   support

           0       0.68      0.44      0.54        43
           1       0.75      0.89      0.81        80

    accuracy                           0.73       123
   macro avg       0.71      0.66      0.67       123
weighted avg       0.72      0.73      0.71       123



In [11]:
results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest",
        "KNN",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy_score(y_test, dt_model.predict(X_test)),
        accuracy_score(y_test, rf_model.predict(X_test)),
        accuracy_score(y_test, knn_model.predict(X_test)),
        accuracy_score(y_test, gb_model.predict(X_test))
    ]
})

results.sort_values(by="Accuracy", ascending=False)

,Model,Accuracy
3,Gradient Boosting,0.731707
1,Random Forest,0.715447
0,Decision Tree,0.642276
2,KNN,0.626016


In [12]:
import pickle

pickle.dump(gb_model, open("../models/rdf.pkl", "wb"))

print("Model saved successfully.")

Model saved successfully.


In [13]:
print(X_train.columns)

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='str')
